spring:
  servlet:
    multipart:
      max-file-size: 5MB
  redis: ## redis
    cluster:
      nodes:
        - 172.31.131.176:9001
        - 172.31.131.176:9002
        - 172.31.131.176:9003
    password: h2+o2=H2O2
    timeout: 3000
    jedis:
      pool:
        min-idle: 2
        max-idle: 5
        max-active: 10
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host:port/db
    username: postgres
    password: xxxx
    hikari:
      connection-test-query: SELECT 1
      idle-timeout: 60000  # 60s空闲
      minimum-idle: 10
      maximum-pool-size: 50
      connection-timeout: 3000 # 连接超时
logging:
  config: classpath:log4j2.xml
springdoc:  # swagger 配置
  swagger-ui:
    path: /${projectName}-api
    enabled: true
  api-docs:
    enabled: true
  packages-to-scan: ${groupId}.web.portal.controller
  default-consumes-media-type: application/json;charset=utf-8
  default-produces-media-type: application/json;charset=utf-8

